#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: func

# STEP: vivado_flow
cd /mnt/c/Users/User/Desktop/compress/M-TECH/RTL_TO_GDS/Tutorial_W3
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /mnt/c/Users/User/Desktop/compress/M-TECH/RTL_TO_GDS/Tutorial_W3/HLS_output//Synthesis/vivado_flow/vivado.tcl


